name: Lint

on: 
  pull_request:
    branches: 
      - develop
      - main
  
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    environment: development
    env:
      NODE_VERSION: 18.13.0
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout 🚀
        uses: actions/checkout@v3.3.0
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Linting ✨
        run: yarn lint
